package com.backend.configuration.controller;

import com.backend.configuration.service.DataTypeService;
import com.backend.core.model.DataType;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/customer/datatypes")
public class DataTypeController {

    @Autowired
    private DataTypeService dataTypeService;

    @PostMapping
    public ResponseEntity<DataType> create(@RequestBody @Valid DataType dataType) {
        if (dataType.getId() != null) {
            throw new IllegalArgumentException("id must not be provided on create; it is generated by the server");
        }

        DataType saved = dataTypeService.create(dataType);
        return new ResponseEntity<>(saved, HttpStatus.CREATED);
    }

    @GetMapping
    public ResponseEntity<List<DataType>> listAll() {
        return ResponseEntity.ok(dataTypeService.listAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<DataType> getById(@PathVariable("id") UUID id) {
        return dataTypeService.findById(id)
                .map(ResponseEntity::ok)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "DataType not found"));
    }

    @PutMapping("/{id}")
    public ResponseEntity<DataType> update(@PathVariable("id") UUID id, @RequestBody @Valid DataType dataType) {
        DataType updated = dataTypeService.update(id, dataType);
        return ResponseEntity.ok(updated);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<?> delete(@PathVariable("id") UUID id) {
        dataTypeService.delete(id);
        return ResponseEntity.noContent().build();
    }

}
