package com.backend.configuration.controller;

import com.backend.configuration.service.DataSetService;
import com.backend.core.model.DataSet;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/customer/datasets")
public class DataSetController {

    @Autowired
    private DataSetService dataSetService;

    @PostMapping
    public ResponseEntity<DataSet> create(@RequestBody @Valid DataSet dataSet) {
        if (dataSet.getId() != null) {
            throw new IllegalArgumentException("id must not be provided on create; it is generated by the server");
        }
        DataSet saved = dataSetService.create(dataSet);
        return new ResponseEntity<>(saved, HttpStatus.CREATED);
    }

    @GetMapping("/tenant/{tenantId}")
    public ResponseEntity<List<DataSet>> listByTenant(@PathVariable("tenantId") UUID tenantId) {
        return ResponseEntity.ok(dataSetService.listByTenant(tenantId));
    }

    @GetMapping("/{id}")
    public ResponseEntity<DataSet> getById(@PathVariable("id") UUID id) {
        return dataSetService.getById(id)
                .map(ResponseEntity::ok)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "DataSet not found"));
    }

    @PutMapping("/{id}")
    public ResponseEntity<DataSet> update(@PathVariable("id") UUID id, @RequestBody @Valid DataSet dataSet) {
        DataSet updated = dataSetService.update(id, dataSet);
        return ResponseEntity.ok(updated);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<?> delete(@PathVariable("id") UUID id) {
        dataSetService.delete(id);
        return ResponseEntity.noContent().build();
    }
}
