package com.backend.configuration.service;

import com.backend.configuration.model.DataSetEntity;
import com.backend.configuration.model.DataTypeEmbeddable;
import com.backend.configuration.repo.DataSetRepository;
import com.backend.core.model.DataSet;
import com.backend.core.model.DataType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class DataSetService {

    @Autowired
    private DataSetRepository dataSetRepository;

    // Create: store dataset in this service (Policy Service owns DS persistence)
    public DataSet create(DataSet dto) {
        if (dto == null) throw new IllegalArgumentException("DataSet cannot be null");
        if (dto.getId() != null)
            throw new IllegalArgumentException("id must not be provided on create; it is generated by the server");

        DataSetEntity entity = toEntity(dto);
        // ensure id generated server-side
        if (entity.getId() == null) entity.setId(UUID.randomUUID());
        DataSetEntity saved = dataSetRepository.save(entity);
        return toDto(saved);
    }

    // List by tenant
    public List<DataSet> listByTenant(UUID tenantId) {
        return dataSetRepository.findByTenantId(tenantId).stream().map(this::toDto).collect(Collectors.toList());
    }

    // Get by id
    public Optional<DataSet> getById(UUID id) {
        return dataSetRepository.findById(id).map(this::toDto);
    }

    // Update: replace dataset content (id must exist)
    public DataSet update(UUID id, DataSet dto) {
        DataSetEntity existing = dataSetRepository.findById(id).orElseThrow(() -> new IllegalArgumentException("DataSet not found"));
        // copy updatable fields
        existing.setName(dto.getName());
        existing.setTenantId(dto.getTenantId());
        existing.setPolicy(dto.getPolicy() == null ? new ArrayList<>() : dto.getPolicy().stream().map(this::toEmbeddable).collect(Collectors.toList()));
        DataSetEntity saved = dataSetRepository.save(existing);
        return toDto(saved);
    }

    // Delete
    public void delete(UUID id) {
        dataSetRepository.deleteById(id);
    }

    // Mapping helpers: Entity <-> DTO
    private DataSet toDto(DataSetEntity e) {
        DataSet dto = new DataSet();
        dto.setId(e.getId());
        dto.setTenantId(e.getTenantId());
        dto.setName(e.getName());
        List<DataType> policy = new ArrayList<>();
        if (e.getPolicy() != null) {
            for (DataTypeEmbeddable emb : e.getPolicy()) {
                DataType dt = new DataType();
                dt.setId(emb.getId());
                dt.setName(emb.getName());
                dt.setDescription(emb.getDescription());
                policy.add(dt);
            }
        }
        dto.setPolicy(policy);
        return dto;
    }

    private DataSetEntity toEntity(DataSet dto) {
        DataSetEntity e = new DataSetEntity();
        // id intentionally not copied from DTO: server generates
        e.setTenantId(dto.getTenantId());
        e.setName(dto.getName());
        List<DataTypeEmbeddable> policy = new ArrayList<>();
        if (dto.getPolicy() != null) {
            for (DataType dt : dto.getPolicy()) {
                policy.add(toEmbeddable(dt));
            }
        }
        e.setPolicy(policy);
        return e;
    }

    private DataTypeEmbeddable toEmbeddable(DataType dt) {
        if (dt == null) return null;
        DataTypeEmbeddable emb = new DataTypeEmbeddable();
        emb.setId(dt.getId());
        emb.setName(dt.getName());
        emb.setDescription(dt.getDescription());
        return emb;
    }

}
