package com.backend.policy.service;

import com.backend.core.model.DataSet;
import com.backend.core.model.DataType;
import com.backend.policy.model.DataSetEntity;
import com.backend.policy.model.DataTypeEmbeddable;
import com.backend.policy.repo.DataSetRepository;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class DataSetService {

    @Autowired
    private DataSetRepository dataSetRepository;

    private static final ObjectMapper MAPPER = new ObjectMapper();

    // Create: store dataset in this service (Policy Service owns DS persistence)
    public DataSet create(DataSet dto) {
        if (dto == null) throw new IllegalArgumentException("DataSet cannot be null");
        if (dto.getId() != null) {
            throw new IllegalArgumentException("id must not be provided on create; it is generated by the server");
        }
        DataSetEntity entity = toEntity(dto);
        DataSetEntity saved = dataSetRepository.save(entity);
        return toDto(saved);
    }

    // List by tenant
    public List<DataSet> listByTenant(UUID tenantId) {
        return dataSetRepository.findByTenantId(tenantId).stream().map(this::toDto).collect(Collectors.toList());
    }

    // Get by id
    public Optional<DataSet> getById(UUID id) {
        return dataSetRepository.findById(id).map(this::toDto);
    }

    // Update: replace dataset content (id must exist)
    public DataSet update(UUID id, DataSet dto) {
        DataSetEntity existing = dataSetRepository.findById(id).orElseThrow(() -> new IllegalArgumentException("DataSet not found"));
        // copy updatable fields
        existing.setName(dto.getName());
        existing.setTenantId(dto.getTenantId());
        existing.setPolicy(dto.getPolicy() == null ? new ArrayList<>() : dto.getPolicy().stream().map(this::toEmbeddable).collect(Collectors.toList()));
        DataSetEntity saved = dataSetRepository.save(existing);
        return toDto(saved);
    }

    // Delete
    public void delete(UUID id) {
        dataSetRepository.deleteById(id);
    }

    // Handle DataType update notification: find datasets referencing this DataType id and update emb fields
    public int handleDataTypeUpdated(DataType dt) {
        if (dt == null || dt.getId() == null) return 0;
        int updatedCount = 0;
        List<DataSetEntity> all = dataSetRepository.findAll();
        for (DataSetEntity ds : all) {
            boolean changed = false;
            if (ds.getPolicy() != null) {
                for (DataTypeEmbeddable emb : ds.getPolicy()) {
                    if (emb != null && dt.getId().equals(emb.getId())) {
                        emb.setName(dt.getName());
                        emb.setDescription(dt.getDescription());
                        emb.setType(dt.getType() == null ? null : dt.getType().name());
                        try {
                            emb.setContent(dt.getContent() == null ? null : MAPPER.writeValueAsString(dt.getContent()));
                        } catch (JsonProcessingException ex) {
                            emb.setContent(null);
                        }
                        emb.setThreshold(dt.getThreshold() == null ? 0.0 : dt.getThreshold());
                        changed = true;
                    }
                }
            }
            if (changed) {
                dataSetRepository.save(ds);
                updatedCount++;
            }
        }
        return updatedCount;
    }

    // Handle DataType deleted notification: remove references to the DataType from datasets
    public int handleDataTypeDeleted(UUID id) {
        if (id == null) return 0;
        int updatedCount = 0;
        List<DataSetEntity> all = dataSetRepository.findAll();
        for (DataSetEntity ds : all) {
            boolean changed = false;
            if (ds.getPolicy() != null) {
                List<DataTypeEmbeddable> remaining = new ArrayList<>();
                for (DataTypeEmbeddable emb : ds.getPolicy()) {
                    if (emb == null) continue;
                    if (id.equals(emb.getId())) {
                        changed = true;
                        continue; // drop this emb
                    }
                    remaining.add(emb);
                }
                if (changed) {
                    ds.setPolicy(remaining);
                }
            }
            if (changed) {
                dataSetRepository.save(ds);
                updatedCount++;
            }
        }
        return updatedCount;
    }

    // Mapping helpers: Entity <-> DTO
    private DataSet toDto(DataSetEntity e) {
        DataSet dto = new DataSet();
        dto.setId(e.getId());
        dto.setTenantId(e.getTenantId());
        dto.setName(e.getName());
        List<DataType> policy = new ArrayList<>();
        if (e.getPolicy() != null) {
            for (DataTypeEmbeddable emb : e.getPolicy()) {
                DataType dt = new DataType();
                dt.setId(emb.getId());
                dt.setName(emb.getName());
                dt.setDescription(emb.getDescription());
                // map back type, content, threshold
                try {
                    if (emb.getType() != null) dt.setType(DataType.Type.valueOf(emb.getType()));
                    if (emb.getContent() != null) {
                        List<String> content = MAPPER.readValue(emb.getContent(), MAPPER.getTypeFactory().constructCollectionType(List.class, String.class));
                        dt.setContent(content);
                    }
                    dt.setThreshold(emb.getThreshold() == null ? 0.0 : emb.getThreshold());
                } catch (JsonProcessingException ex) {
                    // ignore parsing issues and leave content null/empty
                }
                policy.add(dt);
            }
        }
        dto.setPolicy(policy);
        return dto;
    }

    private DataSetEntity toEntity(DataSet dto) {
        DataSetEntity e = new DataSetEntity();
        // id intentionally not copied from DTO: IDs are generated internally by the persistence layer
        e.setTenantId(dto.getTenantId());
        e.setName(dto.getName());
        List<DataTypeEmbeddable> policy = new ArrayList<>();
        if (dto.getPolicy() != null) {
            for (DataType dt : dto.getPolicy()) {
                policy.add(toEmbeddable(dt));
            }
        }
        e.setPolicy(policy);
        return e;
    }

    private DataTypeEmbeddable toEmbeddable(DataType dt) {
        if (dt == null) return null;
        DataTypeEmbeddable emb = new DataTypeEmbeddable();
        emb.setId(dt.getId());
        emb.setName(dt.getName());
        emb.setDescription(dt.getDescription());
        emb.setType(dt.getType() == null ? null : dt.getType().name());
        try {
            emb.setContent(dt.getContent() == null ? null : MAPPER.writeValueAsString(dt.getContent()));
        } catch (JsonProcessingException ex) {
            emb.setContent(null);
        }
        emb.setThreshold(dt.getThreshold() == null ? 0.0 : dt.getThreshold());
        return emb;
    }

}
