package com.backend.configuration.service;

import com.backend.configuration.model.DataTypeEntity;
import com.backend.configuration.repo.DataTypeRepository;
import com.backend.core.model.DataSet;
import com.backend.core.model.DataType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
public class DataSetService {

    @Autowired
    private PolicyServiceClient policyServiceClient;

    @Autowired
    private DataTypeService dataTypeService;

    @Autowired
    private DataTypeRepository dataTypeRepository; // used to fetch DTs from DB

    // Create: enrich DTO with full DataType definitions and forward to Policy Service
    public DataSet create(DataSet dto) {
        if (dto == null) throw new IllegalArgumentException("DataSet cannot be null");
        if (dto.getId() != null)
            throw new IllegalArgumentException("id must not be provided on create; it is generated by the server");

        DataSet enriched = enrichWithDataTypeDefinitions(dto);
        return policyServiceClient.createDataset(enriched);
    }

    // List by tenant: forward to Policy Service (policy DB ops live in Policy Service)
    public List<DataSet> listByTenant(UUID tenantId) {
        return policyServiceClient.listDatasetsByTenant(tenantId);
    }

    // Get by id: forward to Policy Service
    public Optional<DataSet> getById(UUID id) {
        return policyServiceClient.getDataset(id);
    }

    // Update: enrich and forward
    public DataSet update(UUID id, DataSet dto) {
        DataSet enriched = enrichWithDataTypeDefinitions(dto);
        return policyServiceClient.updateDataset(id, enriched);
    }

    // Delete: forward
    public void delete(UUID id) {
        policyServiceClient.deleteDataset(id);
    }

    // Override the existing DS (fetching all NEW content from DB)
    private DataSet enrichWithDataTypeDefinitions(DataSet dto) {
        DataSet copy = new DataSet();
        // ID intentionally not copied from DTO: IDs are generated internally by the policy service
        copy.setTenantId(dto.getTenantId());
        copy.setName(dto.getName());

        List<DataType> enrichedPolicy = new ArrayList<>();
        if (dto.getPolicy() != null) {
            for (DataType dt : dto.getPolicy()) {
                UUID dtId = dt.getId();
                if (dtId == null) throw new IllegalArgumentException("DataType id missing in policy");
                Optional<DataTypeEntity> dataTypeFromDB = dataTypeRepository.findById(dtId);
                if (dataTypeFromDB.isEmpty())
                    throw new IllegalArgumentException("Referenced DataType not found: " + dtId);
                DataType enrichedDataType = dataTypeService.toDto(dataTypeFromDB.get());
                enrichedPolicy.add(enrichedDataType);
            }
        }
        copy.setPolicy(enrichedPolicy);
        return copy;
    }

}
